version: '3'
services:
  metrics:
    build:
      context: ..
      dockerfile: build/Dockerfile
  grafana:
    image: grafana/grafana
    ports:
     - "3000:3000"
    volumes:
     - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus
    volumes:
     - prometheus-storage:/prometheus
     - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
     - metrics
volumes:
  grafana-storage:
  prometheus-storage:
