version: '3'
services:
  metrics:
    build:
      context: ..
      dockerfile: build/Dockerfile
    ports:
     - "127.0.0.1:3001:8080"
  grafana:
    image: grafana/grafana
    ports:
     - "127.0.0.1:3000:3000"
    volumes:
     - grafana-storage:/var/lib/grafana
    environment:
     - GF_SERVER_ROOT_URL=https://hetzner.schmitt.mx
     - GF_AUTH_ANONYMOUS_ENABLED=true
     - GF_AUTH_ANONYMOUS_ORG_NAME=Public
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus
    volumes:
     - prometheus-storage:/prometheus
     - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
     - metrics
volumes:
  grafana-storage:
  prometheus-storage:
