version: '3'
services:
  metrics:
    build:
      context: ..
      dockerfile: build/Dockerfile
  grafana:
    image: grafana/grafana
    volumes:
     - grafana-storage:/var/lib/grafana
    environment:
     - GF_SERVER_ROOT_URL=https://hetzner.schmitt.mx
     - GF_AUTH_ANONYMOUS_ENABLED=true
     - GF_AUTH_ANONYMOUS_ORG_NAME=Public
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus
    volumes:
     - prometheus-storage:/prometheus
     - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
     - metrics
  nginx: 
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - grafana
volumes:
  grafana-storage:
  prometheus-storage:
